Authentication With Login and Register
ctc-uci/get-inspired-frontend pull request #34
Opened 2023-01-31 23:18 UTC by ctc-devops

Authors:
 ### What does this PR contain?
 ### How did you test these changes?
 ### Attach images (if applicable)
 Closes #23

2023-02-01 19:54 UTC, claudeisakeeb requested changes
Functionality overall looks pretty good, just had some comments.

Also, have you guys verified that using generic tags in css doesn't conflict with other files even when we're using module.css?

Please also delete all of the commented lines of code (the places I left comments in are not extensive)

And please fix merge conflicts :)

2023-02-01 19:54 UTC, claudeisakeeb commented on src/App.jsx
>  import React from 'react';
Please change all paths to kebab case

2023-02-01 19:54 UTC, claudeisakeeb commented on src/App.jsx
> +          <Route exact path="/ManageUsersPage" element={<ManageUsersPage />} />
delete /managerUsers and replace the path here with /manage-users

2023-02-01 19:54 UTC, claudeisakeeb commented on src/App.jsx
> +            path="/register"
delete /registerPage and replace the component here with resgisterPage

2023-02-01 19:54 UTC, claudeisakeeb commented on src/App.jsx
> +          <Route
Is this supposed to be the profile route? Or is it something else?

2023-02-01 19:54 UTC, claudeisakeeb commented on src/App.jsx
>  import { Route, Routes, BrowserRouter as Router } from 'react-router-dom';
Can we move all of the "Page" files into the pages folder? ie ManageUsersPage, RegisterPage, HomePage, etc.

2023-02-01 19:54 UTC, claudeisakeeb commented on src/components/Logout.jsx
> +  const handleSubmit2 = async () => {
delete this lol

2023-02-01 19:54 UTC, claudeisakeeb commented on src/components/Logout.jsx
> +      <button type="submit" onClick={handleSubmit2}>
delete

2023-02-01 19:54 UTC, claudeisakeeb commented on src/components/ManageUsers/ManageUsers.jsx
> +      // console.log(
delete this console log

2023-02-01 19:54 UTC, claudeisakeeb commented on src/components/ManageUsers/ManageUsers.jsx
> +  // /**
Delete this since we're not supporting signing in with Google

2023-02-01 19:54 UTC, claudeisakeeb commented on src/components/Register/Register.jsx
> +      // console.log(
delete

2023-02-01 19:54 UTC, claudeisakeeb commented on src/components/Register/Register.jsx
> +    // e.preventDefault();
delete

2023-02-01 19:54 UTC, claudeisakeeb commented on src/components/Register/Register.jsx
> +  // /**
delete

2023-02-01 19:54 UTC, claudeisakeeb commented on src/utils/ProtectedRoute.jsx
> +const userIsAuthenticated = async (roles, cookies) => {
Can we redirect the user to the dashboard if they're already logged in and they try to access /login?

2023-02-02 21:35 UTC, Jacqueline1201 commented on src/App.jsx
> +          <Route
I think it's the route to the manage users page

2023-02-06 00:39 UTC, claudeisakeeb submitted a review, later dismissed

2023-02-06 00:47 UTC, merged