Added the layout and navbar component to app.jsx
ctc-uci/get-inspired-frontend pull request #39
Opened 2023-02-10 02:35 UTC by ctc-devops

Authors:
 ### What does this PR contain?
 ### How did you test these changes?
 ### Attach images (if applicable)
 Closes #29

2023-02-10 05:56 UTC, alanchangxyz requested changes
+ other comments:
- random `Icon` file in this PR; please delete it (this is also preventing switching to your branch for some reason so no functional tests involved in this PR)
- since we are now using yarn instead of npm, there should be no more `package-lock.json`; delete it and just keep changes to `yarn.lock` in the future instead

2023-02-10 05:56 UTC, alanchangxyz commented on src/App.jsx
> +import './App.css';
styles should be imported near the bottom of all imports; also if this is not a global style sheet it should be `module.css`

2023-02-10 05:56 UTC, alanchangxyz commented on src/components/Layout/Layout.jsx
> +Layout.propTypes = {
`propTypes` should be defined before `defaultProps` for good convention

2023-02-10 05:56 UTC, alanchangxyz commented on src/components/Layout/Layout.module.css
> +    width: 80;
80px? 80%? need a unit here

2023-02-10 05:56 UTC, alanchangxyz commented on src/pages/LoginPage/LoginPage.jsx
> +const LoginPage = () => {
going to assume this `LoginPage` was not part of this PR otherwise there are many comments to be left here

2023-02-10 05:56 UTC, alanchangxyz commented on src/App.jsx
>  import AUTH_ROLES from './utils/auth_config';
all pages should be imported, then any utils like `AUTH_ROLES` and styles like css

2023-02-10 05:56 UTC, alanchangxyz commented on src/components/NavBar/NavBar.jsx
> +    <Sider width={200}>
if the width is hardcoded it should be defined as a constant such as
```JavaScript
const SIDER_WIDTH = 200;
```
after the imports in this file

2023-02-10 05:56 UTC, alanchangxyz commented on src/components/NavBar/NavBar.jsx
> +        defaultOpenKeys={['sub1']}
don't know if we need the `defaultOpenKeys` attribute here

2023-02-10 05:56 UTC, alanchangxyz commented on src/components/NavBar/NavBar.jsx
> +        style={{ height: '100%', borderRight: 0 }}
would prefer to define styles in css classes than inline whenever possible

2023-02-10 05:56 UTC, alanchangxyz commented on src/components/NavBar/NavBar.jsx
> +        <Menu.Item key="1" icon={<GlobalOutlined />}>
keys should be more descriptive; aka `gsp-logo` or `dashboard-link`

2023-02-10 05:56 UTC, alanchangxyz commented on src/components/NavBar/NavBar.jsx
> +          <Link to="/Dashboard">Dashboard</Link>
[nit] urls should be in lowercase even though it technically doesn't make a difference in the long term

2023-02-13 00:11 UTC, claudeisakeeb requested changes
Looks pretty good, just a few comments

Also please remove package-lock.json and the new GSP logo you added in assets/images because there's already one in dev

2023-02-13 00:11 UTC, claudeisakeeb commented on src/pages/LoginPage/LoginPage.jsx
> +const LoginPage = () => {
Remove this file

2023-02-13 00:11 UTC, claudeisakeeb commented on src/components/NavBar/NavBar.jsx
> +        </Menu.Item>
Could you please reference App.jsx and replace these links with the correct paths?

ie Query Data should go to "/query-data" etc.

2023-02-13 00:11 UTC, claudeisakeeb commented on src/components/NavBar/NavBar.jsx
> +          <Link to="/Data">View Data</Link>
In the meeting we had with Nancy on Friday we decided to change "View Data" to "Manage Attributes"

Could you rename this?

2023-02-13 00:11 UTC, claudeisakeeb commented on src/components/NavBar/NavBar.jsx
> +        <Menu.Item key="5" icon={<ClockCircleFilled />}>
In the meeting we had with Nancy on Friday we decided to change "Query Data" to "Manage Data"

Could you rename this?

2023-02-13 00:11 UTC, claudeisakeeb commented on src/components/NavBar/NavBar.jsx
> +          <Link to="/Dashboard">Dashboard</Link>
In the Figma it says that the first link is actually "Overview"

Could you rename this?

2023-02-13 00:11 UTC, claudeisakeeb commented on src/App.jsx
> +          <Route element={<Layout />}>
You can actually just go ahead and delete these routes through line 117 because all of the pages are set up in the lines above.

Could you just move<Route element={<Layout />}> to only parent the protected routes?
(ie All of the routes except /login and /register)

2023-02-13 00:11 UTC, claudeisakeeb commented on src/components/NavBar/NavBar.jsx
> +    <Sider width={200}>
Could you also make this navbar collapsible? You can just add the collapsible keyword to the Sider props

2023-02-13 00:11 UTC, claudeisakeeb commented on src/components/NavBar/NavBar.jsx
> +        <Menu.Item key="1" icon={<GlobalOutlined />}>
For this icon you can just make it the Logo.svg file currently in dev

Also please rename this to "Get Inspired"

2023-02-13 00:11 UTC, claudeisakeeb commented on src/components/NavBar/NavBar.jsx
> +        defaultSelectedKeys={['1']}
This makes it so that no matter what page you're on it only highlights the first item.
What we want to do is make it so that if you're on the Add Data page, then the Add Data menu item would be highlighted.

Could you please implement this? One potential solution is having a list that only contains a menu item's key if the path matches the link for that menu item. You can get the path with useLocation from react-router-dom

For example, you can do something like defaultSelectedKeys = {[...path === '/' ? [<dashboard menu item key>] : []}. This code snippet makes it so that the dashboard menu item would be highlighted if the user was on the root path.
You would need to have the same conditional for all of the menu items.

Reach out if you need help with this

2023-02-13 00:11 UTC, claudeisakeeb commented on src/components/NavBar/NavBar.jsx
> +        defaultOpenKeys={['sub1']}
this is only for if the menu has submenus, so we don't need this

2023-02-15 22:23 UTC, ctc-devops commented on src/App.jsx
> +import LoginPage from './pages/LoginPage/LoginPage';
🚫 **[eslint]** <[import/no-unresolved](https://github.com/import-js/eslint-plugin-import/blob/v2.26.0/docs/rules/no-unresolved.md)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unable to resolve path to module './pages/LoginPage/LoginPage'.

2023-02-15 22:23 UTC, ctc-devops commented on src/App.jsx
> +import LoginPage from './pages/LoginPage/LoginPage';
🚫 **[eslint]** <[import/extensions](https://github.com/import-js/eslint-plugin-import/blob/v2.26.0/docs/rules/extensions.md)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Missing file extension for "./pages/LoginPage/LoginPage"

2023-02-15 22:31 UTC, ctc-devops commented on src/App.jsx
> +import './App.css';
🚫 **[eslint]** <[import/no-unresolved](https://github.com/import-js/eslint-plugin-import/blob/v2.26.0/docs/rules/no-unresolved.md)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unable to resolve path to module './App.css'.

2023-02-25 02:41 UTC, ctc-devops commented on src/components/Layout/Layout.jsx
> +import Navbar from '../Navbar/Navbar';
🚫 **[eslint]** <[import/extensions](https://github.com/import-js/eslint-plugin-import/blob/v2.27.5/docs/rules/extensions.md)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Missing file extension for "../Navbar/Navbar"

2023-02-25 02:59 UTC, claudeisakeeb approved these changes

2023-02-25 02:59 UTC, merged